[FIVE-6] Crear Modulo de Login
MakingSense/five-rocking-fingers pull request #6
Opened 2020-09-30 18:16 UTC by gonzalorom

**Descripcion:**
Se debe crear un modulo de Login basado en Cognito.

**Realizado:**
- Instalados paquetes Amazon.AspNetCore.Identity.Cognito.
- Agregados los servicios SignIn, SignUp, User y Configuration.
- Agregadas las clases SignInDTO y SignUpDTO con sus respectivos models.
- Creado servicio para extraccion de credenciales (AWS) desde DB.
- Se agrega filtro de Autentificacion.

_Nota: Filtro Authorize, temporalmente en pausa hasta desarrollo de frontend_

2020-10-02 21:09 UTC, gonzalorom commented
-Se agrega frontend: Pagina Sign in y Sign up.
-Se agrega React Router
-Se migra a Hooks.
-Se agrega validacion de usuario registrado.
-Se crea logout.

2020-10-22 14:07 UTC, egutbrod requested changes

2020-10-22 14:07 UTC, egutbrod commented on FiveRockingFingers/FRF.Web/ClientApp/src/commons/NavMenu.tsx
>  import 'react-pro-sidebar/dist/css/styles.css';
Keep imports sorted

2020-10-22 14:07 UTC, egutbrod commented on FiveRockingFingers/FRF.Web/ClientApp/src/commons/NavMenuItem.tsx
> +                    <p>{`Cliente: ${props.project.client}`}</p>
This code is part of [FIVE-4]

2020-10-22 14:07 UTC, egutbrod commented on FiveRockingFingers/FRF.Web/ClientApp/src/commons/SnackbarError.tsx
> +import Snackbar from '@material-ui/core/Snackbar';
Keep imports sorted

2020-10-22 14:07 UTC, egutbrod commented on FiveRockingFingers/FRF.Web/ClientApp/src/components/Home.tsx
> +import React from 'react';
Keep imports sorted

2020-10-22 14:07 UTC, egutbrod commented on FiveRockingFingers/FRF.Web/ClientApp/src/components/auth/Login.tsx
> +import axios from "axios"
Keep imports sorted

2020-10-22 14:07 UTC, egutbrod commented on FiveRockingFingers/FRF.Web/ClientApp/src/components/auth/Signup.tsx
> +import axios from 'axios'
Keep imports sorted

2020-10-22 14:07 UTC, egutbrod commented on FiveRockingFingers/FRF.Web/ClientApp/src/index.tsx
> -import { createBrowserHistory } from 'history';
Keep imports sorted

2020-10-22 14:07 UTC, egutbrod commented on FiveRockingFingers/FRF.Web/ClientApp/src/router/Routers.tsx
> +import Login from '../components/auth/Login';
Keep imports sorted

2020-10-22 14:07 UTC, egutbrod commented on FiveRockingFingers/FRF.Web/ClientApp/src/router/Routes.tsx
>  import Home from '../components/Home';
Keep imports sorted

2020-10-22 14:07 UTC, egutbrod commented on FiveRockingFingers/FRF.Web/Controllers/BaseApiController.cs
>  using System.Linq;
Sort usings

2020-10-22 14:07 UTC, egutbrod commented on FiveRockingFingers/FRF.Web/Controllers/SignInController.cs
> +        private readonly IMapper Mapper;
Change these private attributes names to _name

2020-10-22 14:07 UTC, egutbrod commented on FiveRockingFingers/FRF.Web/Controllers/SignUpController.cs
> +        private readonly IMapper Mapper;
Change these private attributes names to _name

2020-10-22 14:07 UTC, egutbrod commented on FiveRockingFingers/FRF.Web/Controllers/UserController.cs
> +        public IUserService UserService { get; set; }
Change to:

`private readonly IUserService _userService;`

2020-10-22 17:47 UTC, gonzalorom commented on FiveRockingFingers/FRF.Core/Services/ConfigurationService.cs
> +        public DataAccessContext DataContext { get; set; }
Done!

2020-10-22 17:47 UTC, gonzalorom commented on FiveRockingFingers/FRF.Core/Services/ConfigurationService.cs
> +                var result = ToObject<CognitoConfigurationBase>(resultFromDb);
Done!

2020-10-22 17:47 UTC, gonzalorom commented on FiveRockingFingers/FRF.Core/Services/ISignInService.cs
> +using FRF.Core.Models;
Done!

2020-10-22 17:47 UTC, gonzalorom commented on FiveRockingFingers/FRF.Core/Services/ISignUpService.cs
> +using FRF.Core.Models;
Done!

2020-10-22 17:47 UTC, gonzalorom commented on FiveRockingFingers/FRF.Core/Services/SignInService.cs
> +        private readonly SignInManager<CognitoUser> SignInManager;
Done!

2020-10-22 17:47 UTC, gonzalorom commented on FiveRockingFingers/FRF.Core/Services/SignUpService.cs
> +        private readonly SignInManager<CognitoUser> SignInManager;
Done!

2020-10-22 17:47 UTC, gonzalorom commented on FiveRockingFingers/FRF.Core/Services/UserService.cs
> +using Microsoft.AspNetCore.Identity;
Done!

2020-10-22 17:48 UTC, gonzalorom commented on FiveRockingFingers/FRF.Core/Services/UserService.cs
> +        private readonly SignInManager<CognitoUser> SignInManager;
Done!

2020-10-22 17:48 UTC, gonzalorom commented on FiveRockingFingers/FRF.DataAccess/DataAccessContext.cs
> +            optionsBuilder.UseSqlServer("server=DESKTOP-28EG8E0;database=FiveRockingFingers;trusted_connection=true;");
Done!

2020-10-22 17:48 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/ClientApp/src/App.tsx
> +import { Button } from 'reactstrap';
Done!

2020-10-22 17:49 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/ClientApp/src/commons/LoadingButton.tsx
> +import Fade from "@material-ui/core/Fade";
Done!

2020-10-22 17:49 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/ClientApp/src/commons/NavMenu.tsx
>  import 'react-pro-sidebar/dist/css/styles.css';
Done!

2020-10-22 17:49 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/ClientApp/src/commons/NavMenuItem.tsx
> +                    <p>{`Cliente: ${props.project.client}`}</p>
Done!

2020-10-22 17:49 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/ClientApp/src/commons/SnackbarError.tsx
> +import Snackbar from '@material-ui/core/Snackbar';
Done!

2020-10-22 17:49 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/ClientApp/src/components/Home.tsx
> +import React from 'react';
Done!

2020-10-22 17:49 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/ClientApp/src/components/auth/Login.tsx
> +import axios from "axios"
Done!

2020-10-22 17:49 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/ClientApp/src/components/auth/Signup.tsx
> +import axios from 'axios'
Done!

2020-10-22 17:49 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/ClientApp/src/index.tsx
> -import { createBrowserHistory } from 'history';
Done!

2020-10-22 17:50 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/ClientApp/src/router/Routers.tsx
> +import Login from '../components/auth/Login';
Done!

2020-10-22 17:50 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/ClientApp/src/router/Routes.tsx
>  import Home from '../components/Home';
Done!

2020-10-22 17:50 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/Controllers/BaseApiController.cs
>  using System.Linq;
Done!

2020-10-22 17:50 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/Controllers/SignInController.cs
> +        private readonly IMapper Mapper;
Done!

2020-10-22 17:50 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/Controllers/SignUpController.cs
> +        private readonly IMapper Mapper;
Done!

2020-10-22 17:50 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/Controllers/UserController.cs
> +        public IUserService UserService { get; set; }
Done!

2020-10-23 16:34 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web.Dtos/Users/SignUpDTO.cs
> +        [RegularExpression(@"^((([!#$%&'*+\-/=?^_`{|}~\w])|([!#$%&'*+\-/=?^_`{|}~\w][!#$%&'*+\-/=?^_`{|}~\.\w]{0,}[!#$%&'*+\-/=?^_`{|}~\w]))[@]\w+([-.]\w+)*\.\w+([-.]\w+)*)$")]
Done!

2020-10-26 13:00 UTC, matiasbeckerle commented
This PR is massive hehe. Did you addressed all the requested changes from @egutbrod?

2020-10-26 13:18 UTC, gonzalorom commented
Yes, all the request for change from @egutbrod were resolved. I know it is a massive PR.  We are just doing one PR once we finished with the ticket, In this case, the ticket was an epic. This is something that we can improve in the next springs.

2020-10-26 13:25 UTC, matiasbeckerle commented
Alright. If everything was addressed then let's move forward by merging it. @egutbrod once you're back from your vacations have a look just in case you want anything else to be updated / improved.

2020-10-28 17:01 UTC, manquius requested changes

2020-10-28 19:13 UTC, merged

2020-10-28 19:13 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/Controllers/SignUpController.cs
> +            /*Uncomment this after do.*/
Done.

2020-10-28 19:13 UTC, gonzalorom commented on FiveRockingFingers/FRF.Web/Controllers/SignUpController.cs
> +            /*Clear this after do*/
Done.

2020-10-28 19:13 UTC, gonzalorom commented on FiveRockingFingers/FRF.Core/Services/UserService.cs
> +        /*Uncomment this after do.*/
Done.